### PR TITLE
Updates to latest version of javascript node plugin

### PR DESCRIPTION
**Pull request by michaelruocco**
Is this project still being maintained? If not I would consider taking ownership if you like?

### CODE REVIEW

**Comment by simomat** [comment]
You are right, this project should be taken by someone else. Let me see what's necessary to transfer ownership and how we handle it at plugins.gradle.org

**Comment by simomat** [comment]
@michaelruocco I investigated a little and here are some points we should talk about:

- I can transfer the repository to you or an organization you name, but according the github transfer manual, you must not have a fork to this repo to receive it. I think I should merge your pull request, let you remove your fork and can transfer it to you.
- About [the plugin registration at plugins.gradle.org](https://plugins.gradle.org/plugin/de.infonautika.postman), I think the easiest would be if you just change the plugin id and re-publish it.
What do you think? What did I miss?

**Comment by michaelruocco** [comment]
sounds fine to me, I would be happy to give that a go.

**Comment by simomat** [comment]
Ok, just remove your fork and I can transfer it to you @michaelruocco

**Comment by michaelruocco** [comment]
thanks, done.

**Pull request merged**
